### ISSUE TITLE
Consul API May Not Be Listening For Requests Other Than Localhost

### ISSUE THREAD

**Issue by rjduffner** [newrelic/nri-consul#12]
##### Description of the problem

After setting up the consul integration, we noticed that for data to be reported, the agent on a non leader node has to be able to curl the status api of the leader. In our setup, none of our consul agents listen beyond localhost. This causes a failure where the new relic on host integration cannot report any metrics because the follower cannot talk to the leader.

Do we need to lose all data because we can't get some of the data? Do we need to make api calls against leaders directly?

```
Mar  4 21:17:13 <follower hostname> newrelic-infra[3498]: time="2019-03-04T21:17:13Z" level=error msg="executing data source" data prefix=config/consul error="exit status 1" plugin name=consul stderr="[ERR] Error creating Datacenter entity: Get http://<leader hostname>:8500/v1/agent/self: dial tcp <leader ip>:8500: getsockopt: connection refused\n"
```

##### OS

- [ ] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [X] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by cpheps** [comment]
This does look like an over aggressive collection solution. The integration should be more fault tolerant. We'll log an internal bug for our next maintenance cycle.
