### ISSUE TITLE
Capture Consul Agent/Server Version for NRQL

### ISSUE THREAD

**Issue by j0sh3rs** [newrelic/nri-consul#27]
##### Description of the problem

Feature Request:
Capture consul version (for both agent and datacenter/server) so it can be queryable via NRQL.

As a user of the NR platform, it would be useful for me to be able to see what consul versions I have deployed to my environment that are also registering to newrelic, and create alerts/queries around those for reporting purposes.

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by ccheek21** [comment]
@j0sh3rs Thanks for the request! I don't have a running environment right now to check (in progress getting one spun up), but it looks like we should collect this as part of the inventory collection. It would appear under the `config/consul` prefix on the Infrastructure Inventory page
