### ISSUE TITLE
Integration stalls when a discovered agent does not respond

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-consul#55]
Originally reported here: https://newrelic.slack.com/archives/CP2EWSX7C/p1647964852438629

> The problem has to do with timeouts and the way the OHI fan out is structured. With HCP the leader does not expose the API but we keep making requests that are effectively serial and eventually the Infra Agent gives up on the OHI. I hacked in a bit of code that skips an Agent (in the OHI's sense) after the first network error and that fixes the issue- the OHI reports.

A patch for this can be found in https://github.com/msummers-nr/nri-consul/commit/3678b4a329ccea0ac1c0fd52ab189ce64789f73e

**Comment by msummers-nr** [comment]
We (ODP) have been tasked by NR Partners group to work with Hashi on Consul for HCP, this fix is required for that effort.

**Comment by alvarocabanas** [comment]
Add Timeout to the Documentation.
